#!/bin/sh
# $Id: runNodeAutoTests 2062 2017-08-19 14:25:58Z cxh $
# Run the composite accessors in just this directory using the Node Accessor Host

(cd ../..; mocha hosts/node/test/testNodeOneAuto.js --Dauto=gdp/test/auto)
